package com.DAO;
import java.sql.*; import java.util.*; import com.entity.BookDtls;
public class BookDAOImpl implements BookDAO { private final Connection conn; public BookDAOImpl(Connection c){conn=c;}
 public boolean addBooks(BookDtls b){String q="INSERT INTO book_dtls(bookname,author,price,bookCategory,status,photoname,user_email) VALUES(?,?,?,?,?,?,?)";try(PreparedStatement p=conn.prepareStatement(q)){p.setString(1,b.getBookname());p.setString(2,b.getAuthor());p.setString(3,b.getPrice());p.setString(4,b.getBookCategory());p.setString(5,b.getStatus());p.setString(6,b.getPhotoname());p.setString(7,b.getUser_email());return p.executeUpdate()==1;}catch(SQLException e){e.printStackTrace();return false;}}
 public List<BookDtls> getAllBooks(){return list("SELECT * FROM book_dtls ORDER BY bookId DESC");}
 public BookDtls getBookById(int id){try(PreparedStatement p=conn.prepareStatement("SELECT * FROM book_dtls WHERE bookId=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){if(r.next())return map(r);}}catch(SQLException e){e.printStackTrace();}return null;}
 public boolean updateEditBooks(BookDtls b){try(PreparedStatement p=conn.prepareStatement("UPDATE book_dtls SET bookname=?,author=?,price=?,status=? WHERE bookId=?")){p.setString(1,b.getBookname());p.setString(2,b.getAuthor());p.setString(3,b.getPrice());p.setString(4,b.getStatus());p.setInt(5,b.getBookId());return p.executeUpdate()==1;}catch(SQLException e){e.printStackTrace();return false;}}
 public boolean deleteBooks(int id){try(PreparedStatement p=conn.prepareStatement("DELETE FROM book_dtls WHERE bookId=?")){p.setInt(1,id);return p.executeUpdate()==1;}catch(SQLException e){return false;}}
 public List<BookDtls> getNewBooks(){return limit("New",4);} public List<BookDtls> getOldBooks(){return limit("Old",4);} public List<BookDtls> getRecentBooks(){return list("SELECT * FROM book_dtls WHERE status='Active' ORDER BY bookId DESC LIMIT 4");}
 public List<BookDtls> getAllRecentBook(){return list("SELECT * FROM book_dtls WHERE status='Active' ORDER BY bookId DESC");} public List<BookDtls> getAllNewBook(){return category("New");} public List<BookDtls> getAllOldBook(){return category("Old");}
 public List<BookDtls> getBookByOld(String e,String c){List<BookDtls> a=new ArrayList<>();try(PreparedStatement p=conn.prepareStatement("SELECT * FROM book_dtls WHERE user_email=? AND bookCategory=? ORDER BY bookId DESC")){p.setString(1,e);p.setString(2,c);try(ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));}}catch(SQLException x){x.printStackTrace();}return a;}
 public boolean oldBookDelete(String e,String c,int id){try(PreparedStatement p=conn.prepareStatement("DELETE FROM book_dtls WHERE user_email=? AND bookCategory=? AND bookId=?")){p.setString(1,e);p.setString(2,c);p.setInt(3,id);return p.executeUpdate()==1;}catch(SQLException x){return false;}}
 public List<BookDtls> getBookBySearch(String q){List<BookDtls>a=new ArrayList<>();try(PreparedStatement p=conn.prepareStatement("SELECT * FROM book_dtls WHERE status='Active' AND (LOWER(bookname) LIKE ? OR LOWER(author) LIKE ? OR LOWER(bookCategory) LIKE ?) ORDER BY bookId DESC")){String x="%"+q.toLowerCase()+"%";p.setString(1,x);p.setString(2,x);p.setString(3,x);try(ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));}}catch(SQLException e){e.printStackTrace();}return a;}
 private List<BookDtls> limit(String c,int n){return list("SELECT * FROM book_dtls WHERE bookCategory='"+c+"' AND status='Active' ORDER BY bookId DESC LIMIT "+n);} private List<BookDtls> category(String c){return list("SELECT * FROM book_dtls WHERE bookCategory='"+c+"' AND status='Active' ORDER BY bookId DESC");}
 private List<BookDtls> list(String q){List<BookDtls>a=new ArrayList<>();try(Statement s=conn.createStatement();ResultSet r=s.executeQuery(q)){while(r.next())a.add(map(r));}catch(SQLException e){e.printStackTrace();}return a;}
 private BookDtls map(ResultSet r)throws SQLException{BookDtls b=new BookDtls();b.setBookId(r.getInt("bookId"));b.setBookname(r.getString("bookname"));b.setAuthor(r.getString("author"));b.setPrice(r.getString("price"));b.setBookCategory(r.getString("bookCategory"));b.setStatus(r.getString("status"));b.setPhotoname(r.getString("photoname"));b.setEmail(r.getString("user_email"));return b;}
}
