package com.DAO;
import com.entity.User; import java.sql.*;
public class UserDAOImpl implements UserDAO { private final Connection conn; public UserDAOImpl(Connection c){conn=c;}
 public boolean userRegister(User u){String q="INSERT INTO user(name,email,phno,password,address,landmark,city,state,pincode) VALUES(?,?,?,?,?,?,?,?,?)"; try(PreparedStatement ps=conn.prepareStatement(q)){ps.setString(1,u.getName());ps.setString(2,u.getEmail());ps.setString(3,u.getPhono());ps.setString(4,u.getPassword());ps.setString(5,u.getAddress());ps.setString(6,u.getLandmark());ps.setString(7,u.getCity());ps.setString(8,u.getState());ps.setString(9,u.getPincode());return ps.executeUpdate()==1;}catch(SQLException e){e.printStackTrace();return false;}}
 public User login(String e,String p){try(PreparedStatement ps=conn.prepareStatement("SELECT * FROM user WHERE email=? AND password=?")){ps.setString(1,e);ps.setString(2,p);try(ResultSet rs=ps.executeQuery()){if(rs.next())return map(rs);}}catch(SQLException ex){ex.printStackTrace();}return null;}
 public boolean checkPassword(int id,String p){try(PreparedStatement ps=conn.prepareStatement("SELECT 1 FROM user WHERE id=? AND password=?")){ps.setInt(1,id);ps.setString(2,p);try(ResultSet rs=ps.executeQuery()){return rs.next();}}catch(SQLException e){return false;}}
 public boolean updateProfile(User u){String q="UPDATE user SET name=?,email=?,phno=? WHERE id=?"; try(PreparedStatement ps=conn.prepareStatement(q)){ps.setString(1,u.getName());ps.setString(2,u.getEmail());ps.setString(3,u.getPhono());ps.setInt(4,u.getId());return ps.executeUpdate()==1;}catch(SQLException e){e.printStackTrace();return false;}}
 public boolean checkUser(String e){try(PreparedStatement ps=conn.prepareStatement("SELECT 1 FROM user WHERE email=?")){ps.setString(1,e);try(ResultSet rs=ps.executeQuery()){return rs.next();}}catch(SQLException x){return false;}}
 private User map(ResultSet r)throws SQLException{User u=new User();u.setId(r.getInt("id"));u.setName(r.getString("name"));u.setEmail(r.getString("email"));u.setPhono(r.getString("phno"));u.setPassword(r.getString("password"));u.setAddress(r.getString("address"));u.setLandmark(r.getString("landmark"));u.setCity(r.getString("city"));u.setState(r.getString("state"));u.setPincode(r.getString("pincode"));return u;}
}
